title: Core Web
baseurl: ""
url: ""

# Build settings
markdown: kramdown

gems:
  # - jekyll-seo-tag
  # - jekyll-autoprefixer

sass:
  sass_dir: assets/_sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
